#
#  Makefile for the rockchip can and canfd controller driver.
#

obj-$(CONFIG_CAN_ROCKCHIP)	+= rockchip_can.o
obj-$(CONFIG_CANFD_ROCKCHIP)	+= rockchip_canfd.o
obj-$(CONFIG_CAN_RK3528)	+= rk3528_can.o
