# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BCMDHD)	+= rkwifi/
obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
obj-$(CONFIG_INFINEON_DHD)	+= infineon/
obj-$(CONFIG_RTL8822CS)		+= rtl8822cs/
obj-$(CONFIG_RTL8852BS)		+= rtl8852bs/
